---
title: "P8105 -- Homework 6"
author: "Ngoc Duong - nqd2000"
date: "11/23/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(modelr)
library(mgcv)
```



### Problem 2
```{r}
#Download the data 
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
#getting r-square
weather_df %>% 
lm(tmax ~ tmin, data = .) %>% 
  broom::glance() %>% 
  .[,1]

# calculate log(beta0 * beta1)
weather_df %>% 
lm(tmax ~ tmin, data = .) %>% 
  broom::tidy() %>% 
  select(term, estimate) %>% 
  pivot_wider(.,
              names_from = term, 
              values_from = estimate) %>% 
  janitor::clean_names() %>% 
  mutate(log_beta_prod = log(intercept * tmin, base = exp(1))) %>% 
  .[,3]

```

```{r}
#function returns needed values 
mystats = function(lm){
  mystats = cbind(
  lm %>% 
    broom::glance() %>% 
  .[,1],
  lm %>% 
  broom::tidy() %>% 
  select(term, estimate) %>% 
  pivot_wider(.,
              names_from = term, 
              values_from = estimate) %>% 
  janitor::clean_names() %>% 
  mutate(log_beta_prod = log(intercept * tmin, base = exp(1))) %>% 
  .[,3])
 mystats
}
```

```{r}
# use R built in function modelr
weather_df %>% 
  modelr::bootstrap(n = 3) %>% 
  mutate(models = map(strap, ~lm(tmax ~ tmin, data = .x)),
         results = map(models, mystats)) %>% 
  select(-strap,-models) %>% 
  unnest(results)
```